[tool.poetry]
name = "event_bus_example"
version = "0.1.0"
description = ""
authors = ["Sqvall <masster1987@inbox.ru>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
